DROP TABLE IF EXISTS "Queue";

CREATE TABLE "Queue" (
	Id				SERIAL PRIMARY KEY,
	VHostId 		INT REFERENCES "VHost"(Id),
	Name			VARCHAR(1024),
	Created			TIMESTAMP,
	Deleted			TIMESTAMP,
	IsCurrent		BOOLEAN
)
